apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-ylrgtbth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-ylrgtbth 
  name: go-ylrgtbth
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-ylrgtbth
    weight: 100 
